namespace Asynkron.Agent.Core.Runtime;

/// <summary>
/// EventType represents the category of a runtime event emitted by the
/// agent loop. The names map to the event payload types produced by the
/// TypeScript implementation, so consumers can react in the same fashion.
/// </summary>
public enum EventType
{
    /// <summary>
    /// Status signals general state changes or status updates.
    /// </summary>
    Status,
    
    /// <summary>
    /// AssistantMessage represents a message generated by the agent.
    /// </summary>
    AssistantMessage,
    
    /// <summary>
    /// AssistantDelta represents a streaming chunk (delta) of assistant text.
    /// Hosts can render these incrementally and optionally wait for a final
    /// AssistantMessage with the consolidated content when the stream ends.
    /// </summary>
    AssistantDelta,
    
    /// <summary>
    /// Error is emitted when the runtime hits an unrecoverable error.
    /// </summary>
    Error,
    
    /// <summary>
    /// RequestInput notifies the host that the runtime is ready to
    /// receive further input from the user or automation harness.
    /// </summary>
    RequestInput
}
